// React/projet_integre_equipe2/src/components/Monitor/MonitorOfferList.js
import React, { useState, useEffect } from 'react'
import { useHistory } from 'react-router-dom'
import MonitorNavbar from './MonitorNavbar'
import Footer from '../Footer'
import '../Form.css'
import '../ResponsiveTable.css'
import '../ResponsiveButtons.css'

const MonitorOfferList = () => {
    const [offers, setOffers] = useState([])
    const history = useHistory()
    const historyState = history.location.state
    const monitor = historyState.monitor

    function goToMonitorStudentList(idOffer) {
        history.push(`/MonitorStudentList/${idOffer}`, historyState)
    }

    useEffect(() => {
        const getOffersByMonitor = async () => {
            const offersFromServer = await fetchOffersByMonitor()
            setOffers(offersFromServer.filter((offer) => offer.session === monitor.actualSession))
        }
        getOffersByMonitor()
    }, [monitor.actualSession])

    const fetchOffersByMonitor = async () => {
        const res = await fetch(`http://3.16.148.156:8888/offer/get-all-offers/${monitor.id}`)
        return await res.json()
    }

    const filterOffers = (offer) => {
        return offer.session === monitor.actualSession
    }

    return (
        <div>
            <div className="grad">
                <MonitorNavbar />
                <h2 className="text-center text-light">Mes Offres</h2>
                <div className="p-5">
                    <table className="table table-hover bg-light shadow-lg" id="no-more-tables">
                        <thead>
                            <tr>
                                <th scope="col">Entreprise</th>
                                <th scope="col">Poste</th>
                                <th scope="col">Salaire</th>
                                <th scope="col">Date d'affichage</th>
                                <th scope="col">Validité</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {offers
                                .filter(filterOffers)
                                .map((offer) => (
                                    <tr key={offer.idOffer}>
                                        <td data-title="Entreprise">{offer.companyName}</td>
                                        <td data-title="Poste">{offer.jobTitle}</td>
                                        <td data-title="Salaire">{offer.salary}$</td>
                                        <td data-title="Date d'affichage">{offer.displayDate}</td>
                                        <td data-title="Validité">
                                            <h5>
                                                <span className={`badge ${offer.valid ? 'badge-success' : offer.state === null ? 'badge-warning' : 'badge-danger'}`}>
                                                    {offer.state === null ? "En attente" : offer.state}
                                                </span>
                                            </h5>
                                        </td>
                                        <td className="responsiveWidth">
                                            {
                                                offer.valid ?
                                                    <>
                                                        <button className="btn btn-primary mx-2" onClick={(e) => goToMonitorStudentList(offer.idOffer)}>
                                                            <span className="hideButtonText">Voir étudiants</span>
                                                            <span className="hideButtonIcon"><i className="fas fa-book-open"></i></span>
                                                        </button>
                                                    </>
                                                    : ""
                                            }
                                        </td>
                                    </tr>
                                ))}
                        </tbody>
                    </table>
                </div>
            </div>
            <Footer />
        </div>
    )
}

export default MonitorOfferList

// Vue/projetveille2/src/components/Monitor/MonitorOfferList.vue
<template>
  <div className="grad">
    <MonitorNavbar></MonitorNavbar>
    <h2 className="text-center">Mes Offres</h2>
    <div className="p-5">
      <table className="table table-hover bg-light shadow-lg">
        <thead>
          <tr>
            <th scope="col">Entreprise</th>
            <th scope="col">Poste</th>
            <th scope="col">Salaire</th>
            <th scope="col">Date d'affichage</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="offer in offers" :key="offer.idOffer">
            <th>{{ offer.companyName }}</th>
            <td>{{ offer.jobTitle }}</td>
            <td>{{ offer.salary }}$</td>
            <td>{{ offer.displayDate }}</td>
            <td className="w-25">
              <button className="btn btn-primary mx-2" @click="goToMonitorStudentList(offer.idOffer)">Voir étudiants</button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import MonitorNavbar from "./MonitorNavbar.vue";
import MonitorService from "./MonitorService";
import router from "../../router";

export default {
  name: "MonitorOfferList",
  components: {
    MonitorNavbar,
  },
  data() {
    return {
      offers: this.getOffersByMonitor(),
      
    };
  },
  methods: {
    getOffersByMonitor() {
      var monitorId = this.getMonitorId()
      MonitorService.getOffersByMonitor(monitorId).then((response) => {
        this.offers = response;
      });
    },
    getMonitorId() {
        console.log(this.$route.params)
      if (this.$route.params.monitor !== undefined) {
        var monitor = JSON.parse(this.$route.params.monitor);
        return monitor.id;
      } else {
        return this.$route.params.id;
      }
    },
    goToMonitorStudentList(idOffer){
        console.log(idOffer)
        router.push({name:"MonitorStudentList", params: {idOffer: idOffer, } })
    },
  },
};
</script>

<style></style>
