// React/projet_integre_equipe2/src/components/Supervisor/SupervisorAssignedStudentList.js
import SupervisorNavbar from './SupervisorNavbar'
import { useHistory } from 'react-router-dom'
import React, { useState, useEffect } from 'react'
import './../ResponsiveTable.css'
import './../ResponsiveButtons.css'
import Footer from '../Footer'

const SupervisorAssignedStudentList = () => {
    const [interships, setInterships] = useState([])
    const history = useHistory()
    const historyState = history.location.state
    const supervisor = historyState.supervisor

    useEffect(() => {
        const getInternships = async () => {
            const internshipsFromServer = await fetchInternships(supervisor.id)
            setInterships(internshipsFromServer)
        }
        getInternships()
    }, [])

    const fetchInternships = async (idSuperviseur) => {
        const res = await fetch(`http://3.16.148.156:8888/internship/get-all-internships-by-supervisor/${idSuperviseur}`)
        return await res.json()
    }

    const viewOffer = async (offer) => {
        history.push("/OfferView", offer)
    }

    const filterInternships = (internship) => {
        return internship.session === supervisor.actualSession
    }
    
    return (
        <div>
            <div className="grad">
                <SupervisorNavbar />
                <h2 className="text-center text-light">Liste de mes étudiants</h2>
                <div className="p-5">
                    <table className="table table-hover bg-light shadow-lg" id="no-more-tables">
                        <thead>
                            <tr>
                                <th scope="col">Nom</th>
                                <th scope="col">Entreprise</th>
                                <th scope="col">Poste</th>
                                <th scope="col">Numéro de teléphone de l'étudiant</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {interships
                                .filter(filterInternships)
                                .map((internship) => (
                                    <tr key={internship.idInternship}>
                                        <td data-title="Nom">{internship.student.firstName + " " + internship.student.lastName}</td>
                                        <td data-title="Entreprise">{internship.offer.companyName}</td>
                                        <td data-title="Poste">{internship.offer.jobTitle}</td>
                                        <td data-title="Num. étudiant">{internship.student.telephoneNumber}</td>
                                        <td className="responsiveWidth">
                                            <button className="btn btn-primary mx-2" onClick={e => { e.preventDefault(); viewOffer(internship.offer) }}>
                                                <span className="hideButtonText">Consulter l'offre</span>
                                                <span className="hideButtonIcon"><i className="fas fa-book-open"></i></span>
                                            </button>
                                        </td>
                                    </tr>
                                ))}
                        </tbody>
                    </table>
                </div>
            </div>
            <Footer/>
        </div>
    )
}

export default SupervisorAssignedStudentList

// Vue/projetveille2/src/components/Supevisor/SupervisorAssignedStudentList.vue
<template>
  <div>
    <div className="grad">
      <SupervisorNavbar></SupervisorNavbar>
      <h2 className="text-center">Liste de mes étudiants</h2>
      <div className="p-5">
        <table className="table table-hover bg-light shadow-lg">
          <thead>
            <tr>
              <th scope="col">Nom</th>
              <th scope="col">Prénom</th>
              <th scope="col">Entreprise</th>
              <th scope="col">Nom du poste</th>
              <th scope="col">Numéro de teléphone de l'étudiant</th>
              <th scope="col">Offre</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="internship in internships"
              :key="internship.idInternship"
            >
              <th>{{ internship.student.lastName }}</th>
              <th>{{ internship.student.firstName }}</th>
              <th>{{ internship.offer.companyName }}</th>
              <th>{{ internship.offer.jobTitle }}</th>
              <th>{{ internship.student.telephoneNumber }}</th>
              <td className="w-25">
                <button
                  className="btn btn-primary mx-2"
                  @click="goToViewOffer(internship.offer)"
                >
                  Consulter
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script>
import SupervisorNavbar from "./SupervisorNavbar.vue";
import SupervisorService from "./SupervisorService";
import router from "../../router";

export default {
  name: "SupervisorAssignedStudent",
  components: {
    SupervisorNavbar,
  },
  data() {
    return {
      internships: this.getInternships(),
      supervisor: this.$route.params,
    };
  },
  methods: {
    getInternships() {
      var id = this.getSupervisorId();
      SupervisorService.getInternships(id).then((response) => {
        this.internships = response;
      });
    },
    getSupervisorId() {
      if (this.$route.params.supervisor !== undefined) {
        var supervisor = JSON.parse(this.$route.params.supervisor);
        return supervisor.id;
      } else {
        return this.$route.params.id;
      }
    },
    goToViewOffer(offer) {
      router.push({
        name: "OfferView",
        params: {
          offer: JSON.stringify({ ...offer }),
          supervisor: JSON.stringify({ ...this.supervisor }),
        },
      });
    },
  },
};
</script>

<style></style>
