// React/projet_integre_equipe2/src/components/Admin/AdminLogin.js
import React, { useState } from 'react'
import { useHistory } from 'react-router-dom'
import _ from 'lodash'
import Swal from 'sweetalert2'

const AdminLogin = ({ onLogin, authLogin }) => {
    const [admin, setAdmin] = useState({username: "", password: ""})
    const [error, setError] = useState({credentials:""})
    const history = useHistory()

    const fireSwalError = () => {
        Swal.fire({
            title: 'Nom d\'utilisateur ou mot de passe incorrect',
            icon: 'error',
            position: 'top',
            toast: true,
            timer: 1500,
            showConfirmButton: false,
            width: '480px'
        })
    }

    const onSubmit = (e) => {
        e.preventDefault()
        if (_.isEmpty(admin.username) || _.isEmpty(admin.password)) {
            setError({...error, credentials: "Nom d'utilisateur ou mot de passe incorrect"})
            return
        } else {
            onLogin(admin.username, admin.password) 
                .then((data) => data.username != null ? signIn(data) : fireSwalError())
        }

        function signIn(admin){
            authLogin("admin")
            history.push("/Admin", {admin})
        }
    }  

    return (
        <div>
            <form className="container-fluid" onSubmit={onSubmit}>
                <div className="form-group">
                    <label htmlFor="usernameAdmin" className="text-secondary"><i className="fas fa-user"></i> Nom d'utilisateur: </label>
                    {error.username !== "" ? error.username : ""}
                    <input type="text" className="form-control text-center" id="usernameAdmin" name="username" placeholder="Entrez votre nom d'utilisateur" onChange={(e) => setAdmin({...admin, username: e.target.value}) } required/>
                </div>
                <div className="form-group">
                    <label htmlFor="passwordAdmin" className="text-secondary"><i className="fas fa-lock"></i> Mot de passe: </label>
                    {error.password !== "" ? error.password : ""}
                    <input type="password" className="form-control text-center" id="passwordAdmin" name="password" placeholder="Entrez votre mot de passe" onChange={(e) => setAdmin({...admin, password: e.target.value}) } required/>
                </div>
                <div className="d-flex justify-content-center">
                    <button type="submit" className="btn btn-block grad text-white ">Connexion</button>
                </div>
            </form>
        </div>
    )
}

export default AdminLogin

// Vue/projetveille2/src/components/Login/AdminLogin.vue
<template>
  <div>
    <form className="container-fluid" @submit.prevent="login()">
      <div className="form-group">
        <label htmlFor="usernameAdmin" className="text-secondary"
          ><i className="fas fa-user"></i> Nom d'utilisateur:
        </label>
        <input
          type="text"
          className="form-control text-center"
          id="usernameAdmin"
          name="username"
          placeholder="Entrez votre nom d'utilisateur"
          v-model="admin.username"
        />
      </div>
      <div className="form-group">
        <label htmlFor="passwordAdmin" className="text-secondary"
          ><i className="fas fa-lock"></i> Mot de passe:
        </label>
        <input
          type="password"
          className="form-control text-center"
          id="passwordAdmin"
          name="password"
          placeholder="Entrez votre mot de passe"
          v-model="admin.password"
        />
      </div>
      <div className="d-flex justify-content-center">
        <button type="submit" className="btn btn-block btn-primary grad text-white">
          Connexion
        </button>
      </div>
    </form>
  </div>
</template>

<script>
import router from "../../router";
import LoginService from "./LoginService";
import _ from "lodash";

export default {
  name: "AdminLogin",
  data() {
    return {
      admin: {
        username: "",
        password: "",
      },
      error: {
        error: "",
      },
    };
  },
  methods: {
    login() {
      if (
        !_.isEmpty(this.error.credentials) ||
        _.isEmpty(this.admin.password) ||
        _.isEmpty(this.admin.username)
      ) {
        alert("Matricule ou mot de passe incorrect")
        this.error.error = "Matricule ou mot de passe incorrect";
        return;
      } else {
        LoginService.loginAdmin(
          this.admin.username,
          this.admin.password
        ).then((response) => { 
          response.username != null ? router.push("/Admin", response): alert("Erreur de matricule ou mot de passe")
        });
      }
    },
  },
};
</script>

<style></style>
