// React/projet_integre_equipe2/src/components/StudentLogin.js
import _ from 'lodash'
import React from 'react'
import { useState } from 'react'
import { useHistory } from 'react-router-dom'

const StudentLogin = ({onLogin}) => {
    const [student, setStudent] = useState({matricule: "", password: "" })
    const [error, setError] = useState({credentials:"" })
    const history = useHistory()

    const onSubmit = (e) => {
        e.preventDefault()
        if (!_.isEmpty(error.credentials) || _.isEmpty(student.password) || _.isEmpty(student.matricule)) {
            setError({...error, credentials: "Matricule ou mot de passe incorrect"})
            return
        } else {
            onLogin(student.matricule, student.password)
                .then((data) => data.matricule != null ? history.push("/Student", student) : alert("Erreur de matricule ou mot de passe"))
        }
    }

    return (
        <div>
            <form className="container-fluid" onSubmit={onSubmit}>
                <div className="form-group">
                    {error.credentials !== "" ? error.credentials : ""}
                    <label htmlFor="matriculeStudent" className="text-secondary"><i className="fas fa-id-badge"></i> Matricule: </label>
                    <input type="text" className="form-control text-center" id="matriculeStudent" name="matricule" placeholder="Entrez votre matricule" onChange={(e) => setStudent({...student, matricule: e.target.value}) } required />
                </div>
                <div className="form-group">
                    <label htmlFor="passwordStudent" className="text-secondary"><i className="fas fa-lock"></i> Mot de passe: </label>
                    <input type="password" className="form-control text-center" id="passwordStudent" name="password" placeholder="Entrez votre mot de passe" onChange={(e) => setStudent({...student, password: e.target.value}) } required />
                </div>
                <div className="d-flex justify-content-center">
                    <button type="submit" className="btn btn-block grad text-white ">Connexion</button>
                </div>
            </form>
        </div>
    )
}

export default StudentLogin

// Vue/projetveille2/src/components/Login/StudentLogin.vue
<template>
  <div>
    <form @submit.prevent="login()" class="container-fluid">
      <div class="form-group">
        <label for="matriculeStudent" class="text-secondary">
          <i class="fas fa-id-badge"></i> Matricule:
        </label>
        <input
          type="text"
          class="form-control text-center"
          id="matriculeStudent"
          name="matricule"
          placeholder="Entrez votre matricule"
          v-model="student.matricule"
          required
        />
      </div>
      <div class="form-group">
        <label for="passwordStudent" class="text-secondary">
          <i class="fas fa-lock"></i> Mot de passe:
        </label>
        <input
          type="password"
          class="form-control text-center"
          id="passwordStudent"
          name="password"
          placeholder="Entrez votre mot de passe"
          v-model="student.password"
          required
        />
      </div>
      <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-block btn-primary grad text-white">Connexion</button>
      </div>
    </form>
  </div>
</template>

<script>
import router from "../../router";
import LoginService from "./LoginService";
import _ from "lodash";

export default {
  name: "StudentLogin",
  data() {
    return {
      student: {
        matricule: "",
        password: "",
      },
      error: {
        error: "",
      },
    };
  },
  methods: {
    login() {
      if (
        !_.isEmpty(this.error.credentials) ||
        _.isEmpty(this.student.password) ||
        _.isEmpty(this.student.matricule)
      ) {
        alert("Matricule ou mot de passe incorrect")
        this.error.error = "Matricule ou mot de passe incorrect";
        return;
      } else {
        LoginService.loginStudent(
          this.student.matricule,
          this.student.password
        ).then((response) => { 
          response.matricule != null ? router.push("/Student", response): alert("Erreur de matricule ou mot de passe")
        });
      }
    },
  },
};
</script>

<style>
</style>
