// React/projet_integre_equipe2/src/components/AdminStudentList.js
import React from 'react'
import { useHistory } from 'react-router-dom';
import AdminNavbar from './AdminNavbar';
import { useState, useEffect } from 'react'

const AdminStudentList = () => {
    const [students, setStudents] = useState([])
    const history = useHistory()

    useEffect(() => {
        const getStudents = async () => {
            const studentsFromServer = await fetchStudents()
            setStudents(studentsFromServer)
        }
        getStudents()
    }, [])

    const fetchStudents = async () => {
        const res = await fetch('http://localhost:8888/students/get-all-students')
        return await res.json()
    }

    const viewStudentCvList = async (student) => {
        history.push("/AdminStudentCvList", student)
    }

    const validateStudent = async (student) => {
        const res = await fetch(`http://localhost:8888/students/validate-student/${student.matricule}`,
            {
                method: 'PUT',
                headers: {
                    'Content-type': 'application/json'
                },
                body: JSON.stringify(student)
            })
        const data = await res.json()

        setStudents(
            students.map(
                (student1) => student1.matricule === student.matricule ? {...student1, isCvValid: data.isCvValid} : student1
            )
        )
    }

    return (
        <div className="grad">
            <AdminNavbar/>
            <h2 className="text-center">Liste des étudiants</h2>
            <div className="p-5">
                <table className="table table-hover bg-light shadow-lg">
                    <thead>
                        <tr>
                            <th scope="col">Nom: </th>
                            <th scope="col">Matricule: </th>
                            <th scope="col">Validité du CV: </th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {students.map((student) => (
                            <tr className={`${student.isCvValid ? 'table-success' : 'table-warning'}`} key={student.id}>
                                <th>{student.firstName + " " + student.lastName}</th>
                                <td>{student.matricule}</td>
                                <td>{student.isCvValid ? "Valide" : "En attente"}</td>
                                <td className="w-25">
                                    <button className="btn btn-primary mx-2" onClick={e => { e.preventDefault(); viewStudentCvList(student) }}>Consulter documents</button>
                                    <button className="btn btn-success mx-2" onClick={e => { e.preventDefault(); validateStudent(student) }}>Valider étudiant</button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    )
}

export default AdminStudentList

// Vue/projetveille2/src/components/Admin/AdminStudentList.vue
<template>
  <div className="grad">
    <AdminNavbar></AdminNavbar>
    <h2 className="text-center">Liste des étudiants</h2>
    <div className="p-5">
      <table className="table table-hover bg-light shadow-lg">
        <thead>
          <tr>
            <th scope="col">Nom:</th>
            <th scope="col">Matricule:</th>
            <th scope="col">Validité:</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="student in students"
            :key="student.id"
            :class="`${student.isCvValid ? 'table-success' : 'table-warning'}`"
          >
            <th>{{ student.firstName + " " + student.lastName }}</th>
            <td>{{ student.matricule }}</td>
            <td>{{ student.isCvValid ? "Valide" : "En attente" }}</td>
            <td className="w-25">
              <button
                className="btn btn-primary mx-2"
                @click="viewStudentCvList(student)"
              >
                Consulter documents
              </button>
              <button
                className="btn btn-success mx-2"
                @click="validateStudent(student)"
              >
                Valider étudiant
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import AdminNavbar from "./AdminNavbar.vue";
import AdminService from "./AdminService";
import router from "../../router";

export default {
  name: "AdminStudentList",
  components: {
    AdminNavbar,
  },
  data() {
    return {
      students: this.getStudents(),
      admin: this.$route.params,
      adminId: this.$route.params.id,
    };
  },
  methods: {
    getStudents() {
      AdminService.getAllStudents().then((response) => {
        this.students = response;
      });
    },
    viewStudentCvList(student) {
      router.push({
        name: "AdminStudentCvList",
        params: {
          document: JSON.stringify({ ...document }),
          student: JSON.stringify({ ...student }),
          admin: JSON.stringify({ ...this.admin }),
        },
      });
    },
    validateStudent(student) {
      AdminService.validateStudent(student).then((response) => {
        this.students = this.students.map((student1) =>
          student1.matricule === student.matricule
            ? { ...student1, isCvValid: response.isCvValid }
            : student1
        );
      });
    },
  },
};
</script>

<style></style>
