// React/projet_integre_equipe2/src/components/Student/StudentUploadCV.js
import axios from "axios"
import React, { useState } from 'react'
import _ from 'lodash'
import { useHistory } from 'react-router-dom'
import bsCustomFileInput from 'bs-custom-file-input'
import StudentNavbar from "./StudentNavbar"
import Footer from "../Footer"
import '../Form.css'
import Swal from 'sweetalert2'

const StudentUploadCV = () => {
  const typeNotification = "CV"
  const message = "Un étudiant a déposé un CV"
  const [uploadFile, setUploadFile] = useState()
  const [uploadFileName, setUploadFileName] = useState()
  const history = useHistory()
  const historyState = history.location.state
  const student = historyState.student
  const sessionPrefix = ["winter", "summer"]
  const lastMonthOfTheYear = 11
  const winterStart = 8
  const winterDeadLine = 1
  const summerStart = 2
  const summerDeadLine = 5
  const [notification, setNotification] = useState({
    typeNotification: typeNotification, message: message, session: student.actualSession
  })

  const fireSwalGoodCV = () => {
    Swal.fire({
      toast: true,
      position: 'top',
      icon: 'success',
      title: 'CV téléversé avec succès',
      showConfirmButton: false,
      timer: 2000
    })
  }

  const fireSwalError = () => {
    Swal.fire({
      title: "Une erreur est survenue \n lors du transfert de fichier",
      icon: 'error',
      position: 'top',
      toast: true,
      timer: 2000,
      showConfirmButton: false,
      width: '400px',
    })
  }

  const submitForm = (event) => {
    let documentSession = ""
    event.preventDefault()

    if (typeof (uploadFile) !== 'undefined' && typeof (historyState) !== 'undefined' && !_.isEmpty(uploadFileName)) {
      setDocumentSession()
      var fileSignature = uploadFileName + ":" + student.id + ":" + documentSession
      var fileSignatureJSON = JSON.stringify(fileSignature)
      const formData = new FormData()
      formData.append("uploadFile", uploadFile, fileSignatureJSON)

      axios
        .post("http://localhost:8888/uploadcv", formData, {
          headers: {
            "Content-Type": "multipart/form-data"
          },
        })
        .then((response) => {
          fireSwalGoodCV()
        })
        .then((response) => {
          createNotificationAdmin(notification)
        })
        .catch((error) => {
          fireSwalError()
        })
    } else {
      fireSwalError()
    }

    function setDocumentSession() {
      let sessionDate = new Date()
      let sessionMonth = sessionDate.getMonth() <= winterDeadLine ? lastMonthOfTheYear : sessionDate.getMonth()
      let sessionYear = sessionMonth >= winterStart && sessionMonth <= lastMonthOfTheYear ? sessionDate.getFullYear() + 1 : sessionDate.getFullYear()
      let session = sessionMonth >= winterStart && sessionMonth <= lastMonthOfTheYear ? sessionPrefix[0] + sessionYear
        : sessionMonth >= summerStart && sessionMonth <= summerDeadLine ? sessionPrefix[1] + sessionYear : "Erreur"
      documentSession = session
    }
  }

  const createNotificationAdmin = async (notification) => {
    const result = await fetch('http://localhost:8888/notification/save-notification-for-admin',
      {
        method: 'POST',
        headers: {
          'Content-type': 'application/json'
        },
        body: JSON.stringify(notification)
      })
    return await result.json()
  }

  return (
    <div>
      <div className="grad">
        <StudentNavbar useStudent={student} />
        <div className="d-flex justify-content-center">
          <div className="jumbotron jumbotron-fluid bg-light rounded shadow reactivescreen">
            <form className="container-fluid" onSubmit={submitForm}>
              <h1 className="text-center text-secondary">Téléverser CV</h1>
              <div className="form-group">
                <label htmlFor="fileName" className="text-secondary"><i className="fas fa-file-pdf"></i> Nom du fichier :</label>
                <input type='text' className="form-control form-control-lg" id="fileName" name="fileName" onChange={(e) => setUploadFileName(e.target.value)} />
              </div>
              <div className="form-group">
                <div className="custom-file">
                  <input type="file" className="custom-file-input" accept="application/pdf" id="customFileLangHTML" onChange={(e) => { setUploadFile(e.target.files[0]); bsCustomFileInput.init() }} />
                  <label className="custom-file-label" htmlFor="customFileLangHTML" data-browse="Parcourir">Sélectionner un fichier</label>
                </div>
              </div>
              <div className="d-flex justify-content-center">
                <button type="submit" className="btn btn-block btn-primary text-white ">Envoyer</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}

export default StudentUploadCV

// Vue/projetveille2/src/components/Student/StudentUploadCV.vue
<template>
  <div className="grad">
    <StudentNavbar></StudentNavbar>
    <div className="d-flex justify-content-center">
      <div
        className="jumbotron jumbotron-fluid bg-light rounded w-50 shadow reactivescreen"
      >
        <form className="container-fluid" @submit.prevent="uploadCV()">
          <h1 className="text-center text-secondary">Téléverser CV</h1>
          <div className="form-group">
            <label htmlFor="fileName" className="text-secondary"
              ><i className="fas fa-file-pdf"></i> Nom du fichier :</label
            >
            <input
              type="text"
              className="form-control form-control-lg"
              id="fileName"
              name="fileName"
              v-model="uploadFileName"
            />
          </div>
          <div className="form-group">
            <div className="custom-file">
              <input
                type="file"
                className="custom-file-input"
                accept="application/pdf"
                id="customFileLangHTML"
                v-on:input="setValues"
              />
              <label
                className="custom-file-label"
                htmlFor="customFileLangHTML"
                data-browse="Parcourir"
                >Sélectionner un fichier</label
              >
            </div>
          </div>
          <div className="d-flex justify-content-center">
            <button
              type="submit"
              className="btn btn-block btn-primary text-white "
            >
              Envoyer
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import StudentNavbar from "./StudentNavbar.vue";
import axios from "axios";
import _ from "lodash";
import bsCustomFileInput from "bs-custom-file-input";

export default {
  name: "StudentUploadCV",
  components: {
    StudentNavbar,
  },
  data() {
    return {
      uploadFile: "",
      uploadFileName: "",
      student: this.$route.params,
    };
  },
  methods: {
    beforeMount() {
      this.student = this.$route.params;
    },
    uploadCV() {
      console.log(this.uploadFileName)
      if (
        typeof this.uploadFile !== "undefined" &&
        !_.isEmpty(this.uploadFileName)
      ) {
        var fileSignature = this.uploadFileName + ":" + this.student.id + ":" +"winter";
        var fileSignatureJSON = JSON.stringify(fileSignature);
        const formData = new FormData();
        formData.append("uploadFile", this.uploadFile, fileSignatureJSON);
        axios
          .post("http://localhost:8888/uploadcv", formData, {
            headers: {
              "Content-Type": "multipart/form-data",
            },
          })
          // eslint-disable-next-line no-unused-vars
          .then((response) => {
            alert("Cv téléverser avec succès");
          })
          // eslint-disable-next-line no-unused-vars
          .catch((error) => {
            alert("Une erreur est survenue lors du transfert de fichier");
          });
      } else {
        alert("Veuillez remplir les champs");
      }
    },
    setValues(e) {
    this.uploadFile = e.target.files[0];
    bsCustomFileInput.init();
  },
  },
};
</script>

<style></style>
